package com.ting.domain;

import com.ting.domain.base.BaseArticleData21;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleData21 extends BaseArticleData21<ArticleData21> {
	public static final ArticleData21 dao = new ArticleData21();
}
