package com.ting.domain;

import com.ting.domain.base.BaseCategoryOption;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CategoryOption extends BaseCategoryOption<CategoryOption> {
	public static final CategoryOption dao = new CategoryOption();
}
