package com.ting.domain;

import com.ting.domain.base.BaseCompanySetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CompanySetting extends BaseCompanySetting<CompanySetting> {
	public static final CompanySetting dao = new CompanySetting();
}
