package com.ting.domain;

import com.ting.domain.base.BaseCompany;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Company extends BaseCompany<Company> {
	public static final Company dao = new Company();
}
