package com.ting.domain;

import com.ting.domain.base.BaseFinanceDeposit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinanceDeposit extends BaseFinanceDeposit<FinanceDeposit> {
	public static final FinanceDeposit dao = new FinanceDeposit();
}
