package com.ting.domain;

import com.ting.domain.base.BaseMember;
import com.ting.exception.AuthException;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();

    public void auth(long userid, String username){
        Member m = dao.findFirst("select * from destoon_member where userid=? and username=?", userid, username);
        if(m != null){
            return ;
        }
        throw new AuthException(username, null);
    }

    public Member findByUsername(String username){
        return dao.findFirst("select * from destoon_member where username=?", username);
    }
}
