package com.ting.domain;

import com.ting.domain.base.BaseMessage;

import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Message extends BaseMessage<Message> {

    public static final int QUERY_STATUS = 3;

	public static final Message dao = new Message();

    public static void insert(Mall info, String username, boolean tax){
        Message vo = new Message();
        vo.setAddtime(new Date().getTime());
        vo.setContent(null);
        vo.setFeedback(false);
        vo.setFromuser(username);
        vo.setGroupids(null);
        vo.setIp(null);
        vo.setIsread(false);
        vo.setIssend(false);
//        vo.setStatus(QUERY_STATUS);
        vo.setStyle(info.getItemid()+"");
        vo.setTitle(tax+"");
        vo.setTouser(info.getUsername());
    }
}
