package com.ting.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setItemid(java.math.BigInteger itemid) {
		set("itemid", itemid);
	}

	public java.math.BigInteger getItemid() {
		return get("itemid");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setTypeid(java.lang.Boolean typeid) {
		set("typeid", typeid);
	}

	public java.lang.Boolean getTypeid() {
		return get("typeid");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setFromuser(java.lang.String fromuser) {
		set("fromuser", fromuser);
	}

	public java.lang.String getFromuser() {
		return get("fromuser");
	}

	public void setTouser(java.lang.String touser) {
		set("touser", touser);
	}

	public java.lang.String getTouser() {
		return get("touser");
	}

	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}

	public java.lang.Long getAddtime() {
		return get("addtime");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setIsread(java.lang.Boolean isread) {
		set("isread", isread);
	}

	public java.lang.Boolean getIsread() {
		return get("isread");
	}

	public void setIssend(java.lang.Boolean issend) {
		set("issend", issend);
	}

	public java.lang.Boolean getIssend() {
		return get("issend");
	}

	public void setFeedback(java.lang.Boolean feedback) {
		set("feedback", feedback);
	}

	public java.lang.Boolean getFeedback() {
		return get("feedback");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setGroupids(java.lang.String groupids) {
		set("groupids", groupids);
	}

	public java.lang.String getGroupids() {
		return get("groupids");
	}

}
