package com.ting.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMall<M extends BaseMall<M>> extends Model<M> implements IBean {

	public void setItemid(java.math.BigInteger itemid) {
		set("itemid", itemid);
	}

	public java.math.BigInteger getItemid() {
		return get("itemid");
	}

	public void setCatid(java.lang.Long catid) {
		set("catid", catid);
	}

	public java.lang.Long getCatid() {
		return get("catid");
	}

	public void setMycatid(java.math.BigInteger mycatid) {
		set("mycatid", mycatid);
	}

	public java.math.BigInteger getMycatid() {
		return get("mycatid");
	}

	public void setAreaid(java.lang.Long areaid) {
		set("areaid", areaid);
	}

	public java.lang.Long getAreaid() {
		return get("areaid");
	}

	public void setLevel(java.lang.Boolean level) {
		set("level", level);
	}

	public java.lang.Boolean getLevel() {
		return get("level");
	}

	public void setElite(java.lang.Boolean elite) {
		set("elite", elite);
	}

	public java.lang.Boolean getElite() {
		return get("elite");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setStyle(java.lang.String style) {
		set("style", style);
	}

	public java.lang.String getStyle() {
		return get("style");
	}

	public void setFee(java.lang.Float fee) {
		set("fee", fee);
	}

	public java.lang.Float getFee() {
		return get("fee");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return get("brand");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setStep(java.lang.String step) {
		set("step", step);
	}

	public java.lang.String getStep() {
		return get("step");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}

	public java.lang.String getUnit() {
		return get("unit");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}

	public java.lang.String getTag() {
		return get("tag");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return get("keyword");
	}

	public void setPptword(java.lang.String pptword) {
		set("pptword", pptword);
	}

	public java.lang.String getPptword() {
		return get("pptword");
	}

	public void setHits(java.lang.Long hits) {
		set("hits", hits);
	}

	public java.lang.Long getHits() {
		return get("hits");
	}

	public void setOrders(java.lang.Long orders) {
		set("orders", orders);
	}

	public java.lang.Long getOrders() {
		return get("orders");
	}

	public void setSales(java.lang.Long sales) {
		set("sales", sales);
	}

	public java.lang.Long getSales() {
		return get("sales");
	}

	public void setComments(java.lang.Long comments) {
		set("comments", comments);
	}

	public java.lang.Long getComments() {
		return get("comments");
	}

	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	public java.lang.String getThumb() {
		return get("thumb");
	}

	public void setThumb1(java.lang.String thumb1) {
		set("thumb1", thumb1);
	}

	public java.lang.String getThumb1() {
		return get("thumb1");
	}

	public void setThumb2(java.lang.String thumb2) {
		set("thumb2", thumb2);
	}

	public java.lang.String getThumb2() {
		return get("thumb2");
	}

	public void setRelateName(java.lang.String relateName) {
		set("relate_name", relateName);
	}

	public java.lang.String getRelateName() {
		return get("relate_name");
	}

	public void setRelateId(java.lang.String relateId) {
		set("relate_id", relateId);
	}

	public java.lang.String getRelateId() {
		return get("relate_id");
	}

	public void setRelateTitle(java.lang.String relateTitle) {
		set("relate_title", relateTitle);
	}

	public java.lang.String getRelateTitle() {
		return get("relate_title");
	}

	public void setN1(java.lang.String n1) {
		set("n1", n1);
	}

	public java.lang.String getN1() {
		return get("n1");
	}

	public void setN2(java.lang.String n2) {
		set("n2", n2);
	}

	public java.lang.String getN2() {
		return get("n2");
	}

	public void setN3(java.lang.String n3) {
		set("n3", n3);
	}

	public java.lang.String getN3() {
		return get("n3");
	}

	public void setV1(java.lang.String v1) {
		set("v1", v1);
	}

	public java.lang.String getV1() {
		return get("v1");
	}

	public void setV2(java.lang.String v2) {
		set("v2", v2);
	}

	public java.lang.String getV2() {
		return get("v2");
	}

	public void setV3(java.lang.String v3) {
		set("v3", v3);
	}

	public java.lang.String getV3() {
		return get("v3");
	}

	public void setExpress1(java.lang.Long express1) {
		set("express_1", express1);
	}

	public java.lang.Long getExpress1() {
		return get("express_1");
	}

	public void setExpressName1(java.lang.String expressName1) {
		set("express_name_1", expressName1);
	}

	public java.lang.String getExpressName1() {
		return get("express_name_1");
	}

	public void setFeeStart1(java.math.BigDecimal feeStart1) {
		set("fee_start_1", feeStart1);
	}

	public java.math.BigDecimal getFeeStart1() {
		return get("fee_start_1");
	}

	public void setFeeStep1(java.math.BigDecimal feeStep1) {
		set("fee_step_1", feeStep1);
	}

	public java.math.BigDecimal getFeeStep1() {
		return get("fee_step_1");
	}

	public void setExpress2(java.lang.Long express2) {
		set("express_2", express2);
	}

	public java.lang.Long getExpress2() {
		return get("express_2");
	}

	public void setExpressName2(java.lang.String expressName2) {
		set("express_name_2", expressName2);
	}

	public java.lang.String getExpressName2() {
		return get("express_name_2");
	}

	public void setFeeStart2(java.math.BigDecimal feeStart2) {
		set("fee_start_2", feeStart2);
	}

	public java.math.BigDecimal getFeeStart2() {
		return get("fee_start_2");
	}

	public void setFeeStep2(java.math.BigDecimal feeStep2) {
		set("fee_step_2", feeStep2);
	}

	public java.math.BigDecimal getFeeStep2() {
		return get("fee_step_2");
	}

	public void setExpress3(java.lang.Long express3) {
		set("express_3", express3);
	}

	public java.lang.Long getExpress3() {
		return get("express_3");
	}

	public void setExpressName3(java.lang.String expressName3) {
		set("express_name_3", expressName3);
	}

	public java.lang.String getExpressName3() {
		return get("express_name_3");
	}

	public void setFeeStart3(java.math.BigDecimal feeStart3) {
		set("fee_start_3", feeStart3);
	}

	public java.math.BigDecimal getFeeStart3() {
		return get("fee_start_3");
	}

	public void setFeeStep3(java.math.BigDecimal feeStep3) {
		set("fee_step_3", feeStep3);
	}

	public java.math.BigDecimal getFeeStep3() {
		return get("fee_step_3");
	}

	public void setCod(java.lang.Boolean cod) {
		set("cod", cod);
	}

	public java.lang.Boolean getCod() {
		return get("cod");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}

	public java.lang.Integer getGroupid() {
		return get("groupid");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setVip(java.lang.Integer vip) {
		set("vip", vip);
	}

	public java.lang.Integer getVip() {
		return get("vip");
	}

	public void setValidated(java.lang.Boolean validated) {
		set("validated", validated);
	}

	public java.lang.Boolean getValidated() {
		return get("validated");
	}

	public void setTruename(java.lang.String truename) {
		set("truename", truename);
	}

	public java.lang.String getTruename() {
		return get("truename");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setMsn(java.lang.String msn) {
		set("msn", msn);
	}

	public java.lang.String getMsn() {
		return get("msn");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public void setAli(java.lang.String ali) {
		set("ali", ali);
	}

	public java.lang.String getAli() {
		return get("ali");
	}

	public void setSkype(java.lang.String skype) {
		set("skype", skype);
	}

	public java.lang.String getSkype() {
		return get("skype");
	}

	public void setEditor(java.lang.String editor) {
		set("editor", editor);
	}

	public java.lang.String getEditor() {
		return get("editor");
	}

	public void setEdittime(java.lang.Long edittime) {
		set("edittime", edittime);
	}

	public java.lang.Long getEdittime() {
		return get("edittime");
	}

	public void setEditdate(java.util.Date editdate) {
		set("editdate", editdate);
	}

	public java.util.Date getEditdate() {
		return get("editdate");
	}

	public void setAddtime(java.lang.Long addtime) {
		set("addtime", addtime);
	}

	public java.lang.Long getAddtime() {
		return get("addtime");
	}

	public void setAdddate(java.util.Date adddate) {
		set("adddate", adddate);
	}

	public java.util.Date getAdddate() {
		return get("adddate");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setTemplate(java.lang.String template) {
		set("template", template);
	}

	public java.lang.String getTemplate() {
		return get("template");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setLinkurl(java.lang.String linkurl) {
		set("linkurl", linkurl);
	}

	public java.lang.String getLinkurl() {
		return get("linkurl");
	}

	public void setFilepath(java.lang.String filepath) {
		set("filepath", filepath);
	}

	public java.lang.String getFilepath() {
		return get("filepath");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}

	public void setExtcat(java.lang.String extcat) {
		set("extcat", extcat);
	}

	public java.lang.String getExtcat() {
		return get("extcat");
	}

	public void setNewthumb(java.lang.String newthumb) {
		set("newthumb", newthumb);
	}

	public java.lang.String getNewthumb() {
		return get("newthumb");
	}

}
