package com.ting.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticleData21<M extends BaseArticleData21<M>> extends Model<M> implements IBean {

	public void setItemid(java.math.BigInteger itemid) {
		set("itemid", itemid);
	}

	public java.math.BigInteger getItemid() {
		return get("itemid");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
