package com.ting.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public void setUserid(java.math.BigInteger userid) {
		set("userid", userid);
	}

	public java.math.BigInteger getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setGroupid(java.lang.Integer groupid) {
		set("groupid", groupid);
	}

	public java.lang.Integer getGroupid() {
		return get("groupid");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}

	public java.lang.String getCompany() {
		return get("company");
	}

	public void setLevel(java.lang.Boolean level) {
		set("level", level);
	}

	public java.lang.Boolean getLevel() {
		return get("level");
	}

	public void setValidated(java.lang.Boolean validated) {
		set("validated", validated);
	}

	public java.lang.Boolean getValidated() {
		return get("validated");
	}

	public void setValidator(java.lang.String validator) {
		set("validator", validator);
	}

	public java.lang.String getValidator() {
		return get("validator");
	}

	public void setValidtime(java.lang.Long validtime) {
		set("validtime", validtime);
	}

	public java.lang.Long getValidtime() {
		return get("validtime");
	}

	public void setVip(java.lang.Integer vip) {
		set("vip", vip);
	}

	public java.lang.Integer getVip() {
		return get("vip");
	}

	public void setVipt(java.lang.Integer vipt) {
		set("vipt", vipt);
	}

	public java.lang.Integer getVipt() {
		return get("vipt");
	}

	public void setVipr(java.lang.Integer vipr) {
		set("vipr", vipr);
	}

	public java.lang.Integer getVipr() {
		return get("vipr");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCatid(java.lang.String catid) {
		set("catid", catid);
	}

	public java.lang.String getCatid() {
		return get("catid");
	}

	public void setCatids(java.lang.String catids) {
		set("catids", catids);
	}

	public java.lang.String getCatids() {
		return get("catids");
	}

	public void setAreaid(java.lang.Long areaid) {
		set("areaid", areaid);
	}

	public java.lang.Long getAreaid() {
		return get("areaid");
	}

	public void setMode(java.lang.String mode) {
		set("mode", mode);
	}

	public java.lang.String getMode() {
		return get("mode");
	}

	public void setCapital(java.lang.Float capital) {
		set("capital", capital);
	}

	public java.lang.Float getCapital() {
		return get("capital");
	}

	public void setRegunit(java.lang.String regunit) {
		set("regunit", regunit);
	}

	public java.lang.String getRegunit() {
		return get("regunit");
	}

	public void setSize(java.lang.String size) {
		set("size", size);
	}

	public java.lang.String getSize() {
		return get("size");
	}

	public void setRegyear(java.lang.String regyear) {
		set("regyear", regyear);
	}

	public java.lang.String getRegyear() {
		return get("regyear");
	}

	public void setRegcity(java.lang.String regcity) {
		set("regcity", regcity);
	}

	public java.lang.String getRegcity() {
		return get("regcity");
	}

	public void setSell(java.lang.String sell) {
		set("sell", sell);
	}

	public java.lang.String getSell() {
		return get("sell");
	}

	public void setBuy(java.lang.String buy) {
		set("buy", buy);
	}

	public java.lang.String getBuy() {
		return get("buy");
	}

	public void setBusiness(java.lang.String business) {
		set("business", business);
	}

	public java.lang.String getBusiness() {
		return get("business");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}

	public java.lang.String getTelephone() {
		return get("telephone");
	}

	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}

	public java.lang.String getFax() {
		return get("fax");
	}

	public void setMail(java.lang.String mail) {
		set("mail", mail);
	}

	public java.lang.String getMail() {
		return get("mail");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setPostcode(java.lang.String postcode) {
		set("postcode", postcode);
	}

	public java.lang.String getPostcode() {
		return get("postcode");
	}

	public void setHomepage(java.lang.String homepage) {
		set("homepage", homepage);
	}

	public java.lang.String getHomepage() {
		return get("homepage");
	}

	public void setFromtime(java.lang.Long fromtime) {
		set("fromtime", fromtime);
	}

	public java.lang.Long getFromtime() {
		return get("fromtime");
	}

	public void setTotime(java.lang.Long totime) {
		set("totime", totime);
	}

	public java.lang.Long getTotime() {
		return get("totime");
	}

	public void setStyletime(java.lang.Long styletime) {
		set("styletime", styletime);
	}

	public java.lang.Long getStyletime() {
		return get("styletime");
	}

	public void setThumb(java.lang.String thumb) {
		set("thumb", thumb);
	}

	public java.lang.String getThumb() {
		return get("thumb");
	}

	public void setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
	}

	public java.lang.String getIntroduce() {
		return get("introduce");
	}

	public void setHits(java.lang.Long hits) {
		set("hits", hits);
	}

	public java.lang.Long getHits() {
		return get("hits");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}

	public java.lang.String getKeyword() {
		return get("keyword");
	}

	public void setTemplate(java.lang.String template) {
		set("template", template);
	}

	public java.lang.String getTemplate() {
		return get("template");
	}

	public void setSkin(java.lang.String skin) {
		set("skin", skin);
	}

	public java.lang.String getSkin() {
		return get("skin");
	}

	public void setDomain(java.lang.String domain) {
		set("domain", domain);
	}

	public java.lang.String getDomain() {
		return get("domain");
	}

	public void setIcp(java.lang.String icp) {
		set("icp", icp);
	}

	public java.lang.String getIcp() {
		return get("icp");
	}

	public void setLinkurl(java.lang.String linkurl) {
		set("linkurl", linkurl);
	}

	public java.lang.String getLinkurl() {
		return get("linkurl");
	}

}
