package com.ting.domain.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategoryOption<M extends BaseCategoryOption<M>> extends Model<M> implements IBean {

	public void setOid(java.math.BigInteger oid) {
		set("oid", oid);
	}

	public java.math.BigInteger getOid() {
		return get("oid");
	}

	public void setCatid(java.lang.Long catid) {
		set("catid", catid);
	}

	public java.lang.Long getCatid() {
		return get("catid");
	}

	public void setType(java.lang.Boolean type) {
		set("type", type);
	}

	public java.lang.Boolean getType() {
		return get("type");
	}

	public void setRequired(java.lang.Boolean required) {
		set("required", required);
	}

	public java.lang.Boolean getRequired() {
		return get("required");
	}

	public void setSearch(java.lang.Boolean search) {
		set("search", search);
	}

	public java.lang.Boolean getSearch() {
		return get("search");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setValue(java.lang.String value) {
		set("value", value);
	}

	public java.lang.String getValue() {
		return get("value");
	}

	public void setExtend(java.lang.String extend) {
		set("extend", extend);
	}

	public java.lang.String getExtend() {
		return get("extend");
	}

	public void setListorder(java.lang.Integer listorder) {
		set("listorder", listorder);
	}

	public java.lang.Integer getListorder() {
		return get("listorder");
	}

}
